import React from 'react';
import { useParams, useSearchParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { absenceService } from '../services/absence.service';
import { format } from 'date-fns';
import LoadingSpinner from '../components/UI/LoadingSpinner';
 
export const VerifyQR = () => {
  const { requestId }         = useParams();
  const [searchParams]        = useSearchParams();
  // The QR URL is: /verify/:requestId?code=XXXX
  // We must pass `code` to the backend — without it the backend can't verify.
  const code = searchParams.get('code');
 
  const { data, isLoading, isError } = useQuery({
    queryKey: ['verify', requestId, code],
    queryFn:  () => absenceService.verifyQR(requestId, code).then(r => r.data.data),
    // Don't retry on 400/404 — invalid code is a definitive answer
    retry: (count, err) => err.response?.status >= 500 && count < 2,
    enabled: !!requestId && !!code
  });
 
  // Missing code param — malformed URL
  if (!code) return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 flex items-center justify-center p-4">
      <div className="text-center">
        <div className="text-5xl mb-4">⚠️</div>
        <h1 className="text-xl font-bold text-gray-700 dark:text-gray-200">Invalid QR Link</h1>
        <p className="text-gray-500 dark:text-gray-400 mt-2">
          This QR code is malformed or was not generated by this system.
        </p>
      </div>
    </div>
  );
 
  if (isLoading) return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 flex items-center justify-center">
      <LoadingSpinner label="Verifying request..." />
    </div>
  );
 
  if (isError) return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 flex items-center justify-center p-4">
      <div className="text-center max-w-sm">
        <div className="text-5xl mb-4">❌</div>
        <h1 className="text-xl font-bold text-red-600 dark:text-red-400">
          Invalid or Expired Notice
        </h1>
        <p className="text-gray-500 dark:text-gray-400 mt-2">
          This absence notice could not be verified. It may have expired or
          been tampered with. Please contact the University Clinic directly.
        </p>
      </div>
    </div>
  );
 
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 dark:from-gray-900 dark:to-gray-800 flex items-center justify-center p-4">
      <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-xl max-w-md w-full p-8">
 
        <div className="text-center mb-6">
          <div className="text-4xl mb-2">✅</div>
          <h1 className="text-xl font-bold text-green-600 dark:text-green-400">
            Verified Excused Absence
          </h1>
          <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
            Official Notice — University Health Services
          </p>
        </div>
 
        <div className="space-y-0 divide-y divide-gray-100 dark:divide-gray-700">
          {[
            ['Student',    `${data.student.firstName} ${data.student.lastName}`],
            ['Student ID', data.student.studentId],
            ['Period',     `${format(new Date(data.absenceDateStart), 'MMM d')} – ${format(new Date(data.absenceDateEnd), 'MMM d, yyyy')}`],
            ['Status',     'APPROVED'],
          ].map(([label, value]) => (
            <div key={label} className="flex justify-between py-3">
              <span className="text-sm text-gray-500 dark:text-gray-400">{label}</span>
              <span className="text-sm font-medium text-gray-900 dark:text-white">{value}</span>
            </div>
          ))}
        </div>
 
        {/* Affected courses */}
        <div className="mt-4 pt-4 border-t border-gray-100 dark:border-gray-700">
          <p className="text-xs font-semibold text-gray-400 dark:text-gray-500 uppercase tracking-wider mb-3">
            Affected Courses
          </p>
          <div className="space-y-2">
            {data.affectedCourses?.map((c, i) => (
              <div key={i} className="flex items-center justify-between">
                <div>
                  <span className="text-sm font-mono font-semibold text-gray-800 dark:text-gray-200">
                    {c.courseCode}
                  </span>
                  <span className="text-xs text-gray-500 dark:text-gray-400 ml-2">
                    {c.courseName}
                  </span>
                </div>
                <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${
                  c.acknowledged
                    ? 'bg-green-100 dark:bg-green-900/40 text-green-700 dark:text-green-300'
                    : 'bg-gray-100 dark:bg-gray-700 text-gray-500 dark:text-gray-400'
                }`}>
                  {c.acknowledged ? 'Acknowledged' : 'Pending'}
                </span>
              </div>
            ))}
          </div>
        </div>
 
        {/* Privacy note */}
        <div className="mt-6 p-3 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
          <p className="text-xs text-blue-700 dark:text-blue-300 text-center">
            Medical details are confidential and not disclosed in this notice.
            Reference: <span className="font-mono font-bold">{data.requestId}</span>
          </p>
        </div>
      </div>
    </div>
  );
};
 
export default VerifyQR;